### ISSUE TITLE
桌面端上方的控件会在某些情况下消失并且不能恢复

### ISSUE THREAD

**Issue by yikavan** [AlvISsReimu/arknights-stats#1]
复现方法如下：
将浏览器拖至窗口大小能够触发移动版的时候，通过右上角的按钮进入网页，再将浏览器恢复原窗口大小时上方的控件全部消失。只能通过将窗口大小重新拖至移动版时才能进入其他网页，但是此时将窗口大小恢复时上方的控件依然不会恢复

**Comment by AlvISsReimu** [comment]
谢谢，已修复。
