### ISSUE TITLE
服务器搬家

### ISSUE THREAD

**Issue by AlvISsReimu** [AlvISsReimu/arknights-stats#11]
考虑aws ec2的hk区域，不过首先要完成#10
update：可以不搬家，只用hk的instance做一个代理？

**Comment by invisiblearts** [comment]
https://ak.inva.land 的做法是主服务器放在北美，用 Route 53 指定中国大陆 CNAME 到阿里云东京，nginx 反代到主服务器，然后在用来更新 SSL 证书的脚本里加入同步证书，工作量并不算很大

**Comment by AlvISsReimu** [comment]
update: 已使用cloudflare，效果还好，暂时不考虑搬家或者代理了
